name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: pnpm setup
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Biome check
        run: pnpm biome check

      - name: TypeScript Compile
        run: pnpm compile

      - name: Run tests
        run: pnpm test
