name: Build and Test

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: pnpm setup
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Biome check
        run: pnpm biome check

      - name: Build
        run: pnpm build

      - name: Run tests
        run: pnpm test
